codegenstruct:
	sh -x mkstruct.sh _173 GTimeVal
	sh -x mkstruct.sh _177 GBytes
	sh -x mkstruct.sh _179 GArray
	sh -x mkstruct.sh _181 GByteArray
	sh -x mkstruct.sh _183 GPtrArray
	sh -x mkstruct.sh _273 GError
	sh -x mkstruct.sh _313 GDebugKey
	sh -x mkstruct.sh _538 GRecMutex # Array
	sh -x mkstruct.sh _542 GCond # Array
	sh -x mkstruct.sh _544 GPrivate # Array
	sh -x mkstruct.sh _546 GOnce
	sh -x mkstruct.sh _534 GThread
	sh -x mkstruct.sh _2584 GThreadFunctions
#	sh -x mkstruct.sh _2742 GStaticRWLock # Embedded anon - oops
	sh -x mkstruct.sh _2753 GStaticPrivate
	sh -x mkstruct.sh _601 GAsyncQueue
	sh -x mkstruct.sh _719 GTimeZone
	sh -x mkstruct.sh _737 GDateTime
	sh -x mkstruct.sh _792 GBookmarkFile
	sh -x mkstruct.sh _864 GChecksum
	sh -x mkstruct.sh _880 GIConv
	sh -x mkstruct.sh _898 GData
	sh -x mkstruct.sh _922 GDate
	sh -x mkstruct.sh _995 GDir
	sh -x mkstruct.sh _1047 GMemVTable
	sh -x mkstruct.sh _1069 GNode
	sh -x mkstruct.sh _1103 GList
	sh -x mkstruct.sh _1138 GHashTable
	sh -x mkstruct.sh _1141 GHashTableIter
	sh -x mkstruct.sh _1183 GHmac
	sh -x mkstruct.sh _1195 GHook 
	sh -x mkstruct.sh _1197 GHookList
	sh -x mkstruct.sh _1236 GPollFD
	sh -x mkstruct.sh _1240 GSList
	sh -x mkstruct.sh _1274 GMainContext
	sh -x mkstruct.sh _1276 GMainLoop
	sh -x mkstruct.sh _1278 GSource
	sh -x mkstruct.sh _1280 GSourcePrivate
	sh -x mkstruct.sh _1282 GSourceCallbackFuncs
	sh -x mkstruct.sh _1284 GSourceFuncs
	sh -x mkstruct.sh _1466 GString
	sh -x mkstruct.sh _1504 GIOChannel # Array
	sh -x mkstruct.sh _1506 GIOFuncs
	sh -x mkstruct.sh _1561 GKeyFile
	sh -x mkstruct.sh _1614 GMappedFile
	sh -x mkstruct.sh _1629 GMarkupParseContext
	sh -x mkstruct.sh _1631 GMarkupParser
	sh -x mkstruct.sh _1651 GVariantType
	sh -x mkstruct.sh _1684 GVariant
	sh -x mkstruct.sh _1766 GVariantIter // Array
	sh -x mkstruct.sh _1776 GVariantBuilder // Union
	sh -x mkstruct.sh _1803 GVariantDict Union
	sh -x mkstruct.sh _1832 GLogField
	sh -x mkstruct.sh _1857 GOptionContext
	sh -x mkstruct.sh _1859 GOptionGroup
	sh -x mkstruct.sh _1861 GOptionEntry
	sh -x mkstruct.sh _1903 GPatternSpec
	sh -x mkstruct.sh _1916 GQueue
	sh -x mkstruct.sh _1961 GRand
	sh -x mkstruct.sh _2015 GRegex
	sh -x mkstruct.sh _2017 GMatchInfo
	sh -x mkstruct.sh _2060 GScanner UNION
	sh -x mkstruct.sh _2062 GScannerConfig
	sh -x mkstruct.sh _2092 GSequence
	sh -x mkstruct.sh _2094 GSequenceNode
	sh -x mkstruct.sh _2284 GStringChunk
	sh -x mkstruct.sh _2292 GStrvBuilder
	sh -x mkstruct.sh _2302 GTestCase
	sh -x mkstruct.sh _2304 GTestSuite
	sh -x mkstruct.sh _2390 GThreadPool
	sh -x mkstruct.sh _2408 GTimer
	sh -x mkstruct.sh _2422 GTrashStack
	sh -x mkstruct.sh _2428 GTree
	sh -x mkstruct.sh _2430 GTreeNode
	sh -x mkstruct.sh _2465 GUri
	sh -x mkstruct.sh _2500 GUriParamsIter # Needs Array
	sh -x mkstruct.sh _2522 GAllocator
	sh -x mkstruct.sh _2524 GMemChunk
	sh -x mkstruct.sh _2544 GCache
	sh -x mkstruct.sh _2555 GCompletion
	sh -x mkstruct.sh _2567 GRelation
	sh -x mkstruct.sh _2569 GTuples

#structmeta:
#	../../../../castxml2pony/castxml2pony --xmlin ../../castxml-results/glib.xml -s f3 f16 f17 f18 f20 f21 f22 f38 f39 f40 f55 f56 f57 f58 f59 f60 f61 f62 f63 f64 f65 f66 f69 f70 f71 f72 f73 f74 f75 f76 f77 f78 f79 f80 f81 f82 f83 f84 f85 f86 f87 f88 f89 f90 f91 f92 f93 f94 f95 f96 f97 f98 f99 f100 f101 f102 f103 f104 f107 f108 f109 f110 f111 f113 f114 f115 f116 f117 f118 f119 f120 f121 f122 f123 f124 f130

#use:
#	saxon-he -xi use.xml ../../xsl/makeuse.xsl |tee  ../../test/Glib/use.pony

#usemeta:
#	../../../../castxml2pony/castxml2pony --xmlin ../../castxml-results/glib.xml -u f3 f16 f17 f18 f20 f21 f22 f38 f39 f40 f55 f56 f57 f58 f59 f60 f61 f62 f63 f64 f65 f66 f69 f70 f71 f72 f73 f74 f75 f76 f77 f78 f79 f80 f81 f82 f83 f84 f85 f86 f87 f88 f89 f90 f91 f92 f93 f94 f95 f96 f97 f98 f99 f100 f101 f102 f103 f104 f107 f108 f109 f110 f111 f113 f114 f115 f116 f117 f118 f119 f120 f121 f122 f123 f124 f130

