codegetstruct:
	saxon-he -xi structs.xml ../../xsl/makestruct.xsl struct=_173 renderfields=1  > ../pony-glib/Glib/GTimeVal.pony
	saxon-he -xi structs.xml ../../xsl/makestruct.xsl struct=_177 renderfields=1  > ../pony-glib/Glib/GBytes.pony
	saxon-he -xi structs.xml ../../xsl/makestruct.xsl struct=_179 renderfields=1  > ../pony-glib/Glib/GArray.pony
	saxon-he -xi structs.xml ../../xsl/makestruct.xsl struct=_181 renderfields=1  > ../pony-glib/Glib/GByteArray.pony
	saxon-he -xi structs.xml ../../xsl/makestruct.xsl struct=_183 renderfields=1  > ../pony-glib/Glib/GPtrArray.pony
	saxon-he -xi structs.xml ../../xsl/makestruct.xsl struct=_273 renderfields=1  > ../pony-glib/Glib/GError.pony






structmeta:
	../../../../castxml2pony/castxml2pony --xmlin ../../castxml-results/glib.xml -S
