all:
	castxml --castxml-output=1,0,0 \
		-Iwebkitgtk-2.34.4 \
		-Iglib-2.70.1 \
		-Iglib-2.70.1/glib-2.0 \
		-Iglib-2.70.1/glib-2.0/gobject \
		-Iglib-2.70.1/glib-2.0/gio \
		-Iclang-7.1.0/include \
		-Iglibc-2.32.35/include \
		-Igtk-3.0 \
		-Igtk-3.0/gtk \
		-Igtk-3.0/gdk \
		-Ipango-1.0 \
		-Iharfbuzz-3.0.0/harfbuzz \
		-Iharfbuzz-3.0.0 \
		-Icairo-1.16.0 \
		-Icairo-1.16.0/cairo \
		-Igdk-pixbuf-2.0 \
		-Igdk-pixbuf-2.0/gdk-pixbuf \
		-Iatk-1.0 \
		-Iatk-1.0/atk \
		-Ilibsoup-3.0 \
		-Ilibsoup-3.0/libsoup \
		-Ipango-1.0 \
		-Ipango-1.0/pango \
		-Ifreetype-2.11.1/freetype \
		-Ifreetype-2.11.1/freetype2 \
		all.h
