all:
	ponyc -d .
	GTK_DEBUG=interactive ./test --ponynoscale

clean:
	rm -f Atk/*.pony
	rm -f Cairo/*.pony
	rm -f demo.gresource/*.pony
	rm -f Gdk/*.pony
	rm -f Gio/*.pony
#	rm -f Glib/*.pony
#	rm -f GObject/*.pony
	rm -f Gtk/*.pony
	rm -f Harfbuzz/*.pony
	rm -f Pango/*.pony
