rm Auto/*pony
java -jar /usr/share/java/Saxon-HE.jar -xi structs.xml ../xsl/makestruct.xsl struct=_92 renderfields=0 >> Auto/Tm.pony
java -jar /usr/share/java/Saxon-HE.jar -xi structs.xml ../xsl/makestruct.xsl struct=_173 renderfields=0 >> Auto/GTimeVal.pony
java -jar /usr/share/java/Saxon-HE.jar -xi structs.xml ../xsl/makestruct.xsl struct=_177 renderfields=0 >> Auto/GBytes.pony
java -jar /usr/share/java/Saxon-HE.jar -xi structs.xml ../xsl/makestruct.xsl struct=_179 renderfields=0 >> Auto/GArray.pony
java -jar /usr/share/java/Saxon-HE.jar -xi structs.xml ../xsl/makestruct.xsl struct=_181 renderfields=0 >> Auto/GByteArray.pony
java -jar /usr/share/java/Saxon-HE.jar -xi structs.xml ../xsl/makestruct.xsl struct=_183 renderfields=0 >> Auto/GPtrArray.pony
java -jar /usr/share/java/Saxon-HE.jar -xi structs.xml ../xsl/makestruct.xsl struct=_273 renderfields=0 >> Auto/GError.pony
java -jar /usr/share/java/Saxon-HE.jar -xi structs.xml ../xsl/makestruct.xsl struct=_313 renderfields=0 >> Auto/GDebugKey.pony
java -jar /usr/share/java/Saxon-HE.jar -xi structs.xml ../xsl/makestruct.xsl struct=_534 renderfields=0 >> Auto/GThread.pony
java -jar /usr/share/java/Saxon-HE.jar -xi structs.xml ../xsl/makestruct.xsl struct=_538 renderfields=0 >> Auto/GRecMutex.pony
java -jar /usr/share/java/Saxon-HE.jar -xi structs.xml ../xsl/makestruct.xsl struct=_540 renderfields=0 >> Auto/GRWLock.pony
java -jar /usr/share/java/Saxon-HE.jar -xi structs.xml ../xsl/makestruct.xsl struct=_542 renderfields=0 >> Auto/GCond.pony
java -jar /usr/share/java/Saxon-HE.jar -xi structs.xml ../xsl/makestruct.xsl struct=_544 renderfields=0 >> Auto/GPrivate.pony
java -jar /usr/share/java/Saxon-HE.jar -xi structs.xml ../xsl/makestruct.xsl struct=_546 renderfields=0 >> Auto/GOnce.pony
java -jar /usr/share/java/Saxon-HE.jar -xi structs.xml ../xsl/makestruct.xsl struct=_601 renderfields=0 >> Auto/GAsyncQueue.pony
java -jar /usr/share/java/Saxon-HE.jar -xi structs.xml ../xsl/makestruct.xsl struct=_719 renderfields=0 >> Auto/GTimeZone.pony
java -jar /usr/share/java/Saxon-HE.jar -xi structs.xml ../xsl/makestruct.xsl struct=_737 renderfields=0 >> Auto/GDateTime.pony
java -jar /usr/share/java/Saxon-HE.jar -xi structs.xml ../xsl/makestruct.xsl struct=_792 renderfields=0 >> Auto/GBookmarkFile.pony
java -jar /usr/share/java/Saxon-HE.jar -xi structs.xml ../xsl/makestruct.xsl struct=_864 renderfields=0 >> Auto/GChecksum.pony
java -jar /usr/share/java/Saxon-HE.jar -xi structs.xml ../xsl/makestruct.xsl struct=_880 renderfields=0 >> Auto/GIConv.pony
java -jar /usr/share/java/Saxon-HE.jar -xi structs.xml ../xsl/makestruct.xsl struct=_898 renderfields=0 >> Auto/GData.pony
java -jar /usr/share/java/Saxon-HE.jar -xi structs.xml ../xsl/makestruct.xsl struct=_922 renderfields=0 >> Auto/GDate.pony
java -jar /usr/share/java/Saxon-HE.jar -xi structs.xml ../xsl/makestruct.xsl struct=_995 renderfields=0 >> Auto/GDir.pony
java -jar /usr/share/java/Saxon-HE.jar -xi structs.xml ../xsl/makestruct.xsl struct=_1047 renderfields=0 >> Auto/GMemVTable.pony
java -jar /usr/share/java/Saxon-HE.jar -xi structs.xml ../xsl/makestruct.xsl struct=_1069 renderfields=0 >> Auto/GNode.pony
java -jar /usr/share/java/Saxon-HE.jar -xi structs.xml ../xsl/makestruct.xsl struct=_1103 renderfields=0 >> Auto/GList.pony
java -jar /usr/share/java/Saxon-HE.jar -xi structs.xml ../xsl/makestruct.xsl struct=_1138 renderfields=0 >> Auto/GHashTable.pony
java -jar /usr/share/java/Saxon-HE.jar -xi structs.xml ../xsl/makestruct.xsl struct=_1141 renderfields=0 >> Auto/GHashTableIter.pony
java -jar /usr/share/java/Saxon-HE.jar -xi structs.xml ../xsl/makestruct.xsl struct=_1183 renderfields=0 >> Auto/GHmac.pony
java -jar /usr/share/java/Saxon-HE.jar -xi structs.xml ../xsl/makestruct.xsl struct=_1195 renderfields=0 >> Auto/GHook.pony
java -jar /usr/share/java/Saxon-HE.jar -xi structs.xml ../xsl/makestruct.xsl struct=_1197 renderfields=0 >> Auto/GHookList.pony
java -jar /usr/share/java/Saxon-HE.jar -xi structs.xml ../xsl/makestruct.xsl struct=_1236 renderfields=0 >> Auto/GPollFD.pony
java -jar /usr/share/java/Saxon-HE.jar -xi structs.xml ../xsl/makestruct.xsl struct=_1240 renderfields=0 >> Auto/GSList.pony
java -jar /usr/share/java/Saxon-HE.jar -xi structs.xml ../xsl/makestruct.xsl struct=_1274 renderfields=0 >> Auto/GMainContext.pony
java -jar /usr/share/java/Saxon-HE.jar -xi structs.xml ../xsl/makestruct.xsl struct=_1276 renderfields=0 >> Auto/GMainLoop.pony
java -jar /usr/share/java/Saxon-HE.jar -xi structs.xml ../xsl/makestruct.xsl struct=_1278 renderfields=0 >> Auto/GSource.pony
java -jar /usr/share/java/Saxon-HE.jar -xi structs.xml ../xsl/makestruct.xsl struct=_1280 renderfields=0 >> Auto/GSourcePrivate.pony
java -jar /usr/share/java/Saxon-HE.jar -xi structs.xml ../xsl/makestruct.xsl struct=_1282 renderfields=0 >> Auto/GSourceCallbackFuncs.pony
java -jar /usr/share/java/Saxon-HE.jar -xi structs.xml ../xsl/makestruct.xsl struct=_1284 renderfields=0 >> Auto/GSourceFuncs.pony
java -jar /usr/share/java/Saxon-HE.jar -xi structs.xml ../xsl/makestruct.xsl struct=_1466 renderfields=0 >> Auto/GString.pony
java -jar /usr/share/java/Saxon-HE.jar -xi structs.xml ../xsl/makestruct.xsl struct=_1504 renderfields=0 >> Auto/GIOChannel.pony
java -jar /usr/share/java/Saxon-HE.jar -xi structs.xml ../xsl/makestruct.xsl struct=_1506 renderfields=0 >> Auto/GIOFuncs.pony
java -jar /usr/share/java/Saxon-HE.jar -xi structs.xml ../xsl/makestruct.xsl struct=_1561 renderfields=0 >> Auto/GKeyFile.pony
java -jar /usr/share/java/Saxon-HE.jar -xi structs.xml ../xsl/makestruct.xsl struct=_1614 renderfields=0 >> Auto/GMappedFile.pony
java -jar /usr/share/java/Saxon-HE.jar -xi structs.xml ../xsl/makestruct.xsl struct=_1629 renderfields=0 >> Auto/GMarkupParseContext.pony
java -jar /usr/share/java/Saxon-HE.jar -xi structs.xml ../xsl/makestruct.xsl struct=_1631 renderfields=0 >> Auto/GMarkupParser.pony
java -jar /usr/share/java/Saxon-HE.jar -xi structs.xml ../xsl/makestruct.xsl struct=_1651 renderfields=0 >> Auto/GVariantType.pony
java -jar /usr/share/java/Saxon-HE.jar -xi structs.xml ../xsl/makestruct.xsl struct=_1684 renderfields=0 >> Auto/GVariant.pony
java -jar /usr/share/java/Saxon-HE.jar -xi structs.xml ../xsl/makestruct.xsl struct=_1766 renderfields=0 >> Auto/GVariantIter.pony
java -jar /usr/share/java/Saxon-HE.jar -xi structs.xml ../xsl/makestruct.xsl struct=_1776 renderfields=0 >> Auto/GVariantBuilder.pony
java -jar /usr/share/java/Saxon-HE.jar -xi structs.xml ../xsl/makestruct.xsl struct=_1803 renderfields=0 >> Auto/GVariantDict.pony
java -jar /usr/share/java/Saxon-HE.jar -xi structs.xml ../xsl/makestruct.xsl struct=_1832 renderfields=0 >> Auto/GLogField.pony
java -jar /usr/share/java/Saxon-HE.jar -xi structs.xml ../xsl/makestruct.xsl struct=_1857 renderfields=0 >> Auto/GOptionContext.pony
java -jar /usr/share/java/Saxon-HE.jar -xi structs.xml ../xsl/makestruct.xsl struct=_1859 renderfields=0 >> Auto/GOptionGroup.pony
java -jar /usr/share/java/Saxon-HE.jar -xi structs.xml ../xsl/makestruct.xsl struct=_1861 renderfields=0 >> Auto/GOptionEntry.pony
java -jar /usr/share/java/Saxon-HE.jar -xi structs.xml ../xsl/makestruct.xsl struct=_1903 renderfields=0 >> Auto/GPatternSpec.pony
java -jar /usr/share/java/Saxon-HE.jar -xi structs.xml ../xsl/makestruct.xsl struct=_1916 renderfields=0 >> Auto/GQueue.pony
java -jar /usr/share/java/Saxon-HE.jar -xi structs.xml ../xsl/makestruct.xsl struct=_1961 renderfields=0 >> Auto/GRand.pony
java -jar /usr/share/java/Saxon-HE.jar -xi structs.xml ../xsl/makestruct.xsl struct=_2015 renderfields=0 >> Auto/GRegex.pony
java -jar /usr/share/java/Saxon-HE.jar -xi structs.xml ../xsl/makestruct.xsl struct=_2017 renderfields=0 >> Auto/GMatchInfo.pony
java -jar /usr/share/java/Saxon-HE.jar -xi structs.xml ../xsl/makestruct.xsl struct=_2060 renderfields=0 >> Auto/GScanner.pony
java -jar /usr/share/java/Saxon-HE.jar -xi structs.xml ../xsl/makestruct.xsl struct=_2062 renderfields=0 >> Auto/GScannerConfig.pony
java -jar /usr/share/java/Saxon-HE.jar -xi structs.xml ../xsl/makestruct.xsl struct=_2092 renderfields=0 >> Auto/GSequence.pony
java -jar /usr/share/java/Saxon-HE.jar -xi structs.xml ../xsl/makestruct.xsl struct=_2094 renderfields=0 >> Auto/GSequenceNode.pony
java -jar /usr/share/java/Saxon-HE.jar -xi structs.xml ../xsl/makestruct.xsl struct=_2284 renderfields=0 >> Auto/GStringChunk.pony
java -jar /usr/share/java/Saxon-HE.jar -xi structs.xml ../xsl/makestruct.xsl struct=_2292 renderfields=0 >> Auto/GStrvBuilder.pony
java -jar /usr/share/java/Saxon-HE.jar -xi structs.xml ../xsl/makestruct.xsl struct=_2302 renderfields=0 >> Auto/GTestCase.pony
java -jar /usr/share/java/Saxon-HE.jar -xi structs.xml ../xsl/makestruct.xsl struct=_2304 renderfields=0 >> Auto/GTestSuite.pony
java -jar /usr/share/java/Saxon-HE.jar -xi structs.xml ../xsl/makestruct.xsl struct=_2390 renderfields=0 >> Auto/GThreadPool.pony
java -jar /usr/share/java/Saxon-HE.jar -xi structs.xml ../xsl/makestruct.xsl struct=_2408 renderfields=0 >> Auto/GTimer.pony
java -jar /usr/share/java/Saxon-HE.jar -xi structs.xml ../xsl/makestruct.xsl struct=_2422 renderfields=0 >> Auto/GTrashStack.pony
java -jar /usr/share/java/Saxon-HE.jar -xi structs.xml ../xsl/makestruct.xsl struct=_2428 renderfields=0 >> Auto/GTree.pony
java -jar /usr/share/java/Saxon-HE.jar -xi structs.xml ../xsl/makestruct.xsl struct=_2430 renderfields=0 >> Auto/GTreeNode.pony
java -jar /usr/share/java/Saxon-HE.jar -xi structs.xml ../xsl/makestruct.xsl struct=_2465 renderfields=0 >> Auto/GUri.pony
java -jar /usr/share/java/Saxon-HE.jar -xi structs.xml ../xsl/makestruct.xsl struct=_2500 renderfields=0 >> Auto/GUriParamsIter.pony
java -jar /usr/share/java/Saxon-HE.jar -xi structs.xml ../xsl/makestruct.xsl struct=_2522 renderfields=0 >> Auto/GAllocator.pony
java -jar /usr/share/java/Saxon-HE.jar -xi structs.xml ../xsl/makestruct.xsl struct=_2524 renderfields=0 >> Auto/GMemChunk.pony
java -jar /usr/share/java/Saxon-HE.jar -xi structs.xml ../xsl/makestruct.xsl struct=_2544 renderfields=0 >> Auto/GCache.pony
java -jar /usr/share/java/Saxon-HE.jar -xi structs.xml ../xsl/makestruct.xsl struct=_2555 renderfields=0 >> Auto/GCompletion.pony
java -jar /usr/share/java/Saxon-HE.jar -xi structs.xml ../xsl/makestruct.xsl struct=_2567 renderfields=0 >> Auto/GRelation.pony
java -jar /usr/share/java/Saxon-HE.jar -xi structs.xml ../xsl/makestruct.xsl struct=_2569 renderfields=0 >> Auto/GTuples.pony
java -jar /usr/share/java/Saxon-HE.jar -xi structs.xml ../xsl/makestruct.xsl struct=_2584 renderfields=0 >> Auto/GThreadFunctions.pony
java -jar /usr/share/java/Saxon-HE.jar -xi structs.xml ../xsl/makestruct.xsl struct=_2733 renderfields=0 >> Auto/GStaticRecMutex.pony
java -jar /usr/share/java/Saxon-HE.jar -xi structs.xml ../xsl/makestruct.xsl struct=_2742 renderfields=0 >> Auto/GStaticRWLock.pony
java -jar /usr/share/java/Saxon-HE.jar -xi structs.xml ../xsl/makestruct.xsl struct=_2753 renderfields=0 >> Auto/GStaticPrivate.pony
