rm Auto/*pony
java -jar /usr/share/java/Saxon-HE.jar -xi structs.xml ../xsl/makestruct.xsl struct=_173 renderfields=1 >> Auto/GTimeValStruct.pony
java -jar /usr/share/java/Saxon-HE.jar -xi structs.xml ../xsl/makestruct.xsl struct=_177 renderfields=1 >> Auto/GBytesStruct.pony
java -jar /usr/share/java/Saxon-HE.jar -xi structs.xml ../xsl/makestruct.xsl struct=_179 renderfields=1 >> Auto/GArrayStruct.pony
java -jar /usr/share/java/Saxon-HE.jar -xi structs.xml ../xsl/makestruct.xsl struct=_181 renderfields=1 >> Auto/GByteArrayStruct.pony
java -jar /usr/share/java/Saxon-HE.jar -xi structs.xml ../xsl/makestruct.xsl struct=_183 renderfields=1 >> Auto/GPtrArrayStruct.pony
java -jar /usr/share/java/Saxon-HE.jar -xi structs.xml ../xsl/makestruct.xsl struct=_273 renderfields=1 >> Auto/GErrorStruct.pony
java -jar /usr/share/java/Saxon-HE.jar -xi structs.xml ../xsl/makestruct.xsl struct=_313 renderfields=1 >> Auto/GDebugKeyStruct.pony
java -jar /usr/share/java/Saxon-HE.jar -xi structs.xml ../xsl/makestruct.xsl struct=_534 renderfields=1 >> Auto/GThreadStruct.pony
java -jar /usr/share/java/Saxon-HE.jar -xi structs.xml ../xsl/makestruct.xsl struct=_538 renderfields=1 >> Auto/GRecMutexStruct.pony
#java -jar /usr/share/java/Saxon-HE.jar -xi structs.xml ../xsl/makestruct.xsl struct=_540 renderfields=1 >> Auto/GRWLockStruct.pony
java -jar /usr/share/java/Saxon-HE.jar -xi structs.xml ../xsl/makestruct.xsl struct=_542 renderfields=1 >> Auto/GCondStruct.pony
java -jar /usr/share/java/Saxon-HE.jar -xi structs.xml ../xsl/makestruct.xsl struct=_544 renderfields=1 >> Auto/GPrivateStruct.pony
java -jar /usr/share/java/Saxon-HE.jar -xi structs.xml ../xsl/makestruct.xsl struct=_546 renderfields=1 >> Auto/GOnceStruct.pony
java -jar /usr/share/java/Saxon-HE.jar -xi structs.xml ../xsl/makestruct.xsl struct=_601 renderfields=1 >> Auto/GAsyncQueueStruct.pony
java -jar /usr/share/java/Saxon-HE.jar -xi structs.xml ../xsl/makestruct.xsl struct=_719 renderfields=1 >> Auto/GTimeZoneStruct.pony
java -jar /usr/share/java/Saxon-HE.jar -xi structs.xml ../xsl/makestruct.xsl struct=_737 renderfields=1 >> Auto/GDateTimeStruct.pony
java -jar /usr/share/java/Saxon-HE.jar -xi structs.xml ../xsl/makestruct.xsl struct=_792 renderfields=1 >> Auto/GBookmarkFileStruct.pony
java -jar /usr/share/java/Saxon-HE.jar -xi structs.xml ../xsl/makestruct.xsl struct=_864 renderfields=1 >> Auto/GChecksumStruct.pony
java -jar /usr/share/java/Saxon-HE.jar -xi structs.xml ../xsl/makestruct.xsl struct=_880 renderfields=1 >> Auto/GIConvStruct.pony
java -jar /usr/share/java/Saxon-HE.jar -xi structs.xml ../xsl/makestruct.xsl struct=_898 renderfields=1 >> Auto/GDataStruct.pony
java -jar /usr/share/java/Saxon-HE.jar -xi structs.xml ../xsl/makestruct.xsl struct=_922 renderfields=1 >> Auto/GDateStruct.pony
java -jar /usr/share/java/Saxon-HE.jar -xi structs.xml ../xsl/makestruct.xsl struct=_995 renderfields=1 >> Auto/GDirStruct.pony
java -jar /usr/share/java/Saxon-HE.jar -xi structs.xml ../xsl/makestruct.xsl struct=_1047 renderfields=1 >> Auto/GMemVTableStruct.pony
java -jar /usr/share/java/Saxon-HE.jar -xi structs.xml ../xsl/makestruct.xsl struct=_1069 renderfields=1 >> Auto/GNodeStruct.pony
java -jar /usr/share/java/Saxon-HE.jar -xi structs.xml ../xsl/makestruct.xsl struct=_1103 renderfields=1 >> Auto/GListStruct.pony
java -jar /usr/share/java/Saxon-HE.jar -xi structs.xml ../xsl/makestruct.xsl struct=_1138 renderfields=1 >> Auto/GHashTableStruct.pony
java -jar /usr/share/java/Saxon-HE.jar -xi structs.xml ../xsl/makestruct.xsl struct=_1141 renderfields=1 >> Auto/GHashTableIterStruct.pony
java -jar /usr/share/java/Saxon-HE.jar -xi structs.xml ../xsl/makestruct.xsl struct=_1183 renderfields=1 >> Auto/GHmacStruct.pony
java -jar /usr/share/java/Saxon-HE.jar -xi structs.xml ../xsl/makestruct.xsl struct=_1195 renderfields=1 >> Auto/GHookStruct.pony
java -jar /usr/share/java/Saxon-HE.jar -xi structs.xml ../xsl/makestruct.xsl struct=_1197 renderfields=1 >> Auto/GHookListStruct.pony
java -jar /usr/share/java/Saxon-HE.jar -xi structs.xml ../xsl/makestruct.xsl struct=_1236 renderfields=1 >> Auto/GPollFDStruct.pony
java -jar /usr/share/java/Saxon-HE.jar -xi structs.xml ../xsl/makestruct.xsl struct=_1240 renderfields=1 >> Auto/GSListStruct.pony
java -jar /usr/share/java/Saxon-HE.jar -xi structs.xml ../xsl/makestruct.xsl struct=_1274 renderfields=1 >> Auto/GMainContextStruct.pony
java -jar /usr/share/java/Saxon-HE.jar -xi structs.xml ../xsl/makestruct.xsl struct=_1276 renderfields=1 >> Auto/GMainLoopStruct.pony
java -jar /usr/share/java/Saxon-HE.jar -xi structs.xml ../xsl/makestruct.xsl struct=_1278 renderfields=1 >> Auto/GSourceStruct.pony
java -jar /usr/share/java/Saxon-HE.jar -xi structs.xml ../xsl/makestruct.xsl struct=_1280 renderfields=1 >> Auto/GSourcePrivateStruct.pony
java -jar /usr/share/java/Saxon-HE.jar -xi structs.xml ../xsl/makestruct.xsl struct=_1282 renderfields=1 >> Auto/GSourceCallbackFuncsStruct.pony
java -jar /usr/share/java/Saxon-HE.jar -xi structs.xml ../xsl/makestruct.xsl struct=_1284 renderfields=1 >> Auto/GSourceFuncsStruct.pony
java -jar /usr/share/java/Saxon-HE.jar -xi structs.xml ../xsl/makestruct.xsl struct=_1466 renderfields=1 >> Auto/GStringStruct.pony
java -jar /usr/share/java/Saxon-HE.jar -xi structs.xml ../xsl/makestruct.xsl struct=_1504 renderfields=1 >> Auto/GIOChannelStruct.pony
java -jar /usr/share/java/Saxon-HE.jar -xi structs.xml ../xsl/makestruct.xsl struct=_1506 renderfields=1 >> Auto/GIOFuncsStruct.pony
java -jar /usr/share/java/Saxon-HE.jar -xi structs.xml ../xsl/makestruct.xsl struct=_1561 renderfields=1 >> Auto/GKeyFileStruct.pony
java -jar /usr/share/java/Saxon-HE.jar -xi structs.xml ../xsl/makestruct.xsl struct=_1614 renderfields=1 >> Auto/GMappedFileStruct.pony
java -jar /usr/share/java/Saxon-HE.jar -xi structs.xml ../xsl/makestruct.xsl struct=_1629 renderfields=1 >> Auto/GMarkupParseContextStruct.pony
java -jar /usr/share/java/Saxon-HE.jar -xi structs.xml ../xsl/makestruct.xsl struct=_1631 renderfields=1 >> Auto/GMarkupParserStruct.pony
java -jar /usr/share/java/Saxon-HE.jar -xi structs.xml ../xsl/makestruct.xsl struct=_1651 renderfields=1 >> Auto/GVariantTypeStruct.pony
java -jar /usr/share/java/Saxon-HE.jar -xi structs.xml ../xsl/makestruct.xsl struct=_1684 renderfields=1 >> Auto/GVariantStruct.pony
java -jar /usr/share/java/Saxon-HE.jar -xi structs.xml ../xsl/makestruct.xsl struct=_1766 renderfields=1 >> Auto/GVariantIterStruct.pony
java -jar /usr/share/java/Saxon-HE.jar -xi structs.xml ../xsl/makestruct.xsl struct=_1776 renderfields=1 >> Auto/GVariantBuilderStruct.pony
java -jar /usr/share/java/Saxon-HE.jar -xi structs.xml ../xsl/makestruct.xsl struct=_1803 renderfields=1 >> Auto/GVariantDictStruct.pony
java -jar /usr/share/java/Saxon-HE.jar -xi structs.xml ../xsl/makestruct.xsl struct=_1832 renderfields=1 >> Auto/GLogFieldStruct.pony
java -jar /usr/share/java/Saxon-HE.jar -xi structs.xml ../xsl/makestruct.xsl struct=_1857 renderfields=1 >> Auto/GOptionContextStruct.pony
java -jar /usr/share/java/Saxon-HE.jar -xi structs.xml ../xsl/makestruct.xsl struct=_1859 renderfields=1 >> Auto/GOptionGroupStruct.pony
java -jar /usr/share/java/Saxon-HE.jar -xi structs.xml ../xsl/makestruct.xsl struct=_1861 renderfields=1 >> Auto/GOptionEntryStruct.pony
java -jar /usr/share/java/Saxon-HE.jar -xi structs.xml ../xsl/makestruct.xsl struct=_1903 renderfields=1 >> Auto/GPatternSpecStruct.pony
java -jar /usr/share/java/Saxon-HE.jar -xi structs.xml ../xsl/makestruct.xsl struct=_1916 renderfields=1 >> Auto/GQueueStruct.pony
java -jar /usr/share/java/Saxon-HE.jar -xi structs.xml ../xsl/makestruct.xsl struct=_1961 renderfields=1 >> Auto/GRandStruct.pony
java -jar /usr/share/java/Saxon-HE.jar -xi structs.xml ../xsl/makestruct.xsl struct=_2015 renderfields=1 >> Auto/GRegexStruct.pony
java -jar /usr/share/java/Saxon-HE.jar -xi structs.xml ../xsl/makestruct.xsl struct=_2017 renderfields=1 >> Auto/GMatchInfoStruct.pony
#java -jar /usr/share/java/Saxon-HE.jar -xi structs.xml ../xsl/makestruct.xsl struct=_2060 renderfields=1 >> Auto/GScannerStruct.pony
java -jar /usr/share/java/Saxon-HE.jar -xi structs.xml ../xsl/makestruct.xsl struct=_2062 renderfields=1 >> Auto/GScannerConfigStruct.pony
java -jar /usr/share/java/Saxon-HE.jar -xi structs.xml ../xsl/makestruct.xsl struct=_2092 renderfields=1 >> Auto/GSequenceStruct.pony
java -jar /usr/share/java/Saxon-HE.jar -xi structs.xml ../xsl/makestruct.xsl struct=_2094 renderfields=1 >> Auto/GSequenceNodeStruct.pony
java -jar /usr/share/java/Saxon-HE.jar -xi structs.xml ../xsl/makestruct.xsl struct=_2284 renderfields=1 >> Auto/GStringChunkStruct.pony
java -jar /usr/share/java/Saxon-HE.jar -xi structs.xml ../xsl/makestruct.xsl struct=_2292 renderfields=1 >> Auto/GStrvBuilderStruct.pony
java -jar /usr/share/java/Saxon-HE.jar -xi structs.xml ../xsl/makestruct.xsl struct=_2302 renderfields=1 >> Auto/GTestCaseStruct.pony
java -jar /usr/share/java/Saxon-HE.jar -xi structs.xml ../xsl/makestruct.xsl struct=_2304 renderfields=1 >> Auto/GTestSuiteStruct.pony
java -jar /usr/share/java/Saxon-HE.jar -xi structs.xml ../xsl/makestruct.xsl struct=_2390 renderfields=1 >> Auto/GThreadPoolStruct.pony
java -jar /usr/share/java/Saxon-HE.jar -xi structs.xml ../xsl/makestruct.xsl struct=_2408 renderfields=1 >> Auto/GTimerStruct.pony
java -jar /usr/share/java/Saxon-HE.jar -xi structs.xml ../xsl/makestruct.xsl struct=_2422 renderfields=1 >> Auto/GTrashStackStruct.pony
java -jar /usr/share/java/Saxon-HE.jar -xi structs.xml ../xsl/makestruct.xsl struct=_2428 renderfields=1 >> Auto/GTreeStruct.pony
java -jar /usr/share/java/Saxon-HE.jar -xi structs.xml ../xsl/makestruct.xsl struct=_2430 renderfields=1 >> Auto/GTreeNodeStruct.pony
java -jar /usr/share/java/Saxon-HE.jar -xi structs.xml ../xsl/makestruct.xsl struct=_2465 renderfields=1 >> Auto/GUriStruct.pony
java -jar /usr/share/java/Saxon-HE.jar -xi structs.xml ../xsl/makestruct.xsl struct=_2500 renderfields=1 >> Auto/GUriParamsIterStruct.pony
java -jar /usr/share/java/Saxon-HE.jar -xi structs.xml ../xsl/makestruct.xsl struct=_2522 renderfields=1 >> Auto/GAllocatorStruct.pony
java -jar /usr/share/java/Saxon-HE.jar -xi structs.xml ../xsl/makestruct.xsl struct=_2524 renderfields=1 >> Auto/GMemChunkStruct.pony
java -jar /usr/share/java/Saxon-HE.jar -xi structs.xml ../xsl/makestruct.xsl struct=_2544 renderfields=1 >> Auto/GCacheStruct.pony
java -jar /usr/share/java/Saxon-HE.jar -xi structs.xml ../xsl/makestruct.xsl struct=_2555 renderfields=1 >> Auto/GCompletionStruct.pony
java -jar /usr/share/java/Saxon-HE.jar -xi structs.xml ../xsl/makestruct.xsl struct=_2567 renderfields=1 >> Auto/GRelationStruct.pony
java -jar /usr/share/java/Saxon-HE.jar -xi structs.xml ../xsl/makestruct.xsl struct=_2569 renderfields=1 >> Auto/GTuplesStruct.pony
java -jar /usr/share/java/Saxon-HE.jar -xi structs.xml ../xsl/makestruct.xsl struct=_2584 renderfields=1 >> Auto/GThreadFunctionsStruct.pony
#java -jar /usr/share/java/Saxon-HE.jar -xi structs.xml ../xsl/makestruct.xsl struct=_2733 renderfields=1 >> Auto/GStaticRecMutexStruct.pony
#java -jar /usr/share/java/Saxon-HE.jar -xi structs.xml ../xsl/makestruct.xsl struct=_2742 renderfields=1 >> Auto/GStaticRWLockStruct.pony
java -jar /usr/share/java/Saxon-HE.jar -xi structs.xml ../xsl/makestruct.xsl struct=_2753 renderfields=1 >> Auto/GStaticPrivateStruct.pony
