codegenstructs:
	rm -f ../../test/Crypto/*
	sh -x mkstruct.sh _136 BIO BIO
	sh -x mkstruct.sh _196 X509 X509
	sh -x mkstruct.sh _206 X509Name X509Name
	sh -x mkstruct.sh _1025 BIOMethod BIOMethod
	sh -x mkprim.sh 0 PEM PEM
