struct GVariantType
struct GUri
struct GTrashStack
struct GThread
struct GSourceFuncs
struct GSequenceNode
struct GPtrArray
struct GPatternSpec
struct GPollFD
struct GDebugKey
struct GMemVTable
struct GMainContext
struct GError
struct GVariant
struct GLogField
struct GIOChannel
struct Valisttag
struct GByteArray
struct GBytes
struct GSource
struct GList
struct GSList
struct GIConv
struct GData
struct GDate
struct GTimeVal
struct GHookList
struct GHashTable
struct GHook
