#structatk:
#	../../../../castxml2pony/castxml2pony --xmlin ../../castxml-results/gtk-3.xml -s f404 f405 f406 f407 f408 f409 f410 f411 f412 f413 f414 f415 f416 f417 f418 f419 f420 f421 f422 f423 f424 f425 f426 f427 f428 f429 f430 f431 f432 f433 f434 f435 f436


all:
	rm -f ../../test/Atk/*
	sh -x mkstruct.sh _11094 ../../test/Atk/AtkAttribute.pony
	sh -x mkstruct.sh _11096 ../../test/Atk/AtkImplementor.pony
	sh -x mkstruct.sh _11098 ../../test/Atk/AtkImplementorIface.pony
	sh -x mkstruct.sh _11100 ../../test/Atk/AtkObject.pony
	sh -x mkstruct.sh _11102 ../../test/Atk/AtkObjectClass.pony
	sh -x mkstruct.sh _11108 ../../test/Atk/AtkPropertyValues.pony
	sh -x mkstruct.sh _11104 ../../test/Atk/AtkRelationSet.pony
	sh -x mkstruct.sh _11400 ../../test/Atk/AtkRelationSetClass.pony
	sh -x mkstruct.sh _11106 ../../test/Atk/AtkStateSet.pony
	sh -x mkstruct.sh _11432 ../../test/Atk/AtkStateSetClass.pony
	sh -x mkstruct.sh _11145 ../../test/Atk/AtkAction.pony
	sh -x mkstruct.sh _11147 ../../test/Atk/AtkActionIface.pony
	sh -x mkstruct.sh _11157 ../../test/Atk/AtkUtil.pony
	sh -x mkstruct.sh _11159 ../../test/Atk/AtkUtilClass.pony
	sh -x mkstruct.sh _11161 ../../test/Atk/AtkKeyEventStruct.pony
	sh -x mkstruct.sh _11186 ../../test/Atk/AtkComponent.pony
	sh -x mkstruct.sh _11188 ../../test/Atk/AtkComponentIface.pony
	sh -x mkstruct.sh _11191 ../../test/Atk/AtkRectangle.pony
	sh -x mkstruct.sh _11211 ../../test/Atk/AtkDocument.pony
	sh -x mkstruct.sh _11213 ../../test/Atk/AtkDocumentIface.pony
	sh -x mkstruct.sh _11227 ../../test/Atk/AtkText.pony
	sh -x mkstruct.sh _11229 ../../test/Atk/AtkTextIface.pony
	sh -x mkstruct.sh _11235 ../../test/Atk/AtkTextRectangle.pony
	sh -x mkstruct.sh _11237 ../../test/Atk/AtkTextRange.pony
	sh -x mkstruct.sh _11270 ../../test/Atk/AtkEditableText.pony
	sh -x mkstruct.sh _11272 ../../test/Atk/AtkEditableTextIface.pony
	sh -x mkstruct.sh _11295 ../../test/Atk/AtkGObjectAccessible.pony
	sh -x mkstruct.sh _11297 ../../test/Atk/AtkGObjectAccessibleClass.pony
	sh -x mkstruct.sh _11304 ../../test/Atk/AtkHyperlink.pony
	sh -x mkstruct.sh _11306 ../../test/Atk/AtkHyperlinkClass.pony
	sh -x mkstruct.sh _11317 ../../test/Atk/AtkHyperlinkImpl.pony
	sh -x mkstruct.sh _11319 ../../test/Atk/AtkHyperlinkImplIface.pony
	sh -x mkstruct.sh _11323 ../../test/Atk/AtkHypertext.pony
	sh -x mkstruct.sh _11325 ../../test/Atk/AtkHypertextIface.pony
	sh -x mkstruct.sh _11331 ../../test/Atk/AtkImage.pony
	sh -x mkstruct.sh _11333 ../../test/Atk/AtkImageIface.pony
	sh -x mkstruct.sh _11341 ../../test/Atk/AtkNoOpObject.pony
	sh -x mkstruct.sh _11343 ../../test/Atk/AtkNoOpObjectClass.pony
	sh -x mkstruct.sh _11347 ../../test/Atk/AtkObjectFactory.pony
	sh -x mkstruct.sh _11349 ../../test/Atk/AtkObjectFactoryClass.pony
	sh -x mkstruct.sh _11355 ../../test/Atk/AtkNoOpObjectFactory.pony
	sh -x mkstruct.sh _11357 ../../test/Atk/AtkNoOpObjectFactoryClass.pony
	sh -x mkstruct.sh _11361 ../../test/Atk/AtkPlug.pony
	sh -x mkstruct.sh _11363 ../../test/Atk/AtkPlugClass.pony
	sh -x mkstruct.sh _11369 ../../test/Atk/AtkRange.pony
	sh -x mkstruct.sh _11378 ../../test/Atk/AtkRegistry.pony
	sh -x mkstruct.sh _11379 ../../test/Atk/AtkRegistryClass.pony
	sh -x mkstruct.sh _11387 ../../test/Atk/AtkRelation.pony
	sh -x mkstruct.sh _11389 ../../test/Atk/AtkRelationClass.pony
	sh -x mkstruct.sh _11412 ../../test/Atk/AtkSelection.pony
	sh -x mkstruct.sh _11414 ../../test/Atk/AtkSelectionIface.pony
	sh -x mkstruct.sh _11424 ../../test/Atk/AtkSocket.pony
#	sh -x mkstruct.sh _11426 ../../test/Atk/AtkSocketClass.pony
	sh -x mkstruct.sh _11446 ../../test/Atk/AtkStreamableContent.pony
	sh -x mkstruct.sh _11448 ../../test/Atk/AtkStreamableContentIface.pony
	sh -x mkstruct.sh _11455 ../../test/Atk/AtkTable.pony
	sh -x mkstruct.sh _11457 ../../test/Atk/AtkTableIface.pony
	sh -x mkstruct.sh _11489 ../../test/Atk/AtkTableCell.pony
	sh -x mkstruct.sh _11491 ../../test/Atk/AtkTableCellIface.pony
	sh -x mkstruct.sh _11501 ../../test/Atk/AtkMisc.pony
	sh -x mkstruct.sh _11503 ../../test/Atk/AtkMiscClass.pony
	sh -x mkstruct.sh _11510 ../../test/Atk/AtkValue.pony
	sh -x mkstruct.sh _11512 ../../test/Atk/AtkValueIface.pony
	sh -x mkstruct.sh _11529 ../../test/Atk/AtkWindow.pony
	sh -x mkstruct.sh _11531 ../../test/Atk/AtkWindowIface.pony
