#structcairo:
#	 ../../../../castxml2pony/castxml2pony --xmlin ../../castxml-results/gtk-3.xml -s f347

codegencairo:
	rm -f ../../test/Cairo/*
	sh -x mkstruct.sh _9219 ../../test/Cairo/Cairo.pony
	sh -x mkstruct.sh _9221 ../../test/Cairo/Cairosurface.pony
	sh -x mkstruct.sh _9223 ../../test/Cairo/Cairodevice.pony
	sh -x mkstruct.sh _9225 ../../test/Cairo/Cairomatrix.pony
	sh -x mkstruct.sh _9227 ../../test/Cairo/Cairopattern.pony
	sh -x mkstruct.sh _9230 ../../test/Cairo/Cairouserdatakey.pony
	sh -x mkstruct.sh _9240 ../../test/Cairo/Cairorectangleint.pony
	sh -x mkstruct.sh _9319 ../../test/Cairo/Cairorectangle.pony
	sh -x mkstruct.sh _9321 ../../test/Cairo/Cairorectanglelist.pony
	sh -x mkstruct.sh _9327 ../../test/Cairo/Cairoscaledfont.pony
	sh -x mkstruct.sh _9329 ../../test/Cairo/Cairofontface.pony
	sh -x mkstruct.sh _9355 ../../test/Cairo/Cairofontoptions.pony
	sh -x mkstruct.sh _9455 ../../test/Cairo/Cairopath.pony
	sh -x mkstruct.sh _9617 ../../test/Cairo/Cairoregion.pony
