#structpango:
#	../../../../castxml2pony/castxml2pony --xmlin ../../castxml-results/gtk-3.xml -s f304 f305 f306 f307 f308 f309 f310 f312 f313 f314 f315 f316


codegenharf:
	rm -f ../../test/Harfbuzz/*
	sh -x mkstruct.sh _8126 ../../test/Harfbuzz/Hblanguageimplt.pony
	sh -x mkstruct.sh _8137 ../../test/Harfbuzz/Hbuserdatakeyt.pony
	sh -x mkstruct.sh _8140 ../../test/Harfbuzz/Hbfeaturet.pony
	sh -x mkstruct.sh _8144 ../../test/Harfbuzz/Hbvariationt.pony
	sh -x mkstruct.sh _8155 ../../test/Harfbuzz/Hbblobt.pony
	sh -x mkstruct.sh _8177 ../../test/Harfbuzz/Hbunicodefuncst.pony
	sh -x mkstruct.sh _8207 ../../test/Harfbuzz/Hbsett.pony
	sh -x mkstruct.sh _8240 ../../test/Harfbuzz/Hbfacet.pony
	sh -x mkstruct.sh _8266 ../../test/Harfbuzz/Hbfontt.pony
	sh -x mkstruct.sh _8268 ../../test/Harfbuzz/Hbfontfuncst.pony
	sh -x mkstruct.sh _8278 ../../test/Harfbuzz/Hbfontextentst.pony
	sh -x mkstruct.sh _8280 ../../test/Harfbuzz/Hbglyphextentst.pony
	sh -x mkstruct.sh _8373 ../../test/Harfbuzz/Hbglyphinfot.pony
	sh -x mkstruct.sh _8378 ../../test/Harfbuzz/Hbglyphpositiont.pony
	sh -x mkstruct.sh _8380 ../../test/Harfbuzz/Hbsegmentpropertiest.pony
	sh -x mkstruct.sh _8384 ../../test/Harfbuzz/Hbbuffert.pony
	sh -x mkstruct.sh _8467 ../../test/Harfbuzz/Hbmapt.pony
	sh -x mkstruct.sh _8486 ../../test/Harfbuzz/Hbshapeplant.pony
